### ISSUE TITLE
Support for Promise.allSettled

### ISSUE THREAD

**Issue by jog068** [supermacro/neverthrow#564]

**Comment by rjoydip** [comment]
@jog068 `Promise.allSettled` supports and works fine.

### Example:

```ts
fromPromise(
  Promise.allSettled([
    Promise.resolve("Success"),
    Promise.reject("Error"),
    Promise.resolve(1),
  ]), 
  () => new Error('Promise allSettled error')
)
```

### Results:

```ts
Ok {
  value: [
    {
      status: "fulfilled",
      value: "Success",
    },
    {
      reason: "Error",
      status: "rejected",
    },
    {
      status: "fulfilled",
      value: 1,
    },
  ],
}
```
<hr />

### Example:

```ts
fromPromise(
  Promise.all([
    Promise.resolve("Success"),
    Promise.reject("Error"),
    Promise.resolve(1),
  ]), 
  () => new Error('Promise all error')
)
```

### Results:

```ts
Err {
  error: Error: Promise all error
    at file:///C:/Users/rjoydip/codebase/oss-issue-solving/neverthrow/564/main.ts:8:56
    at file:///C:/Users/rjoydip/AppData/Local/deno/npm/registry.npmjs.org/neverthrow/7.0.1/dist/index.cjs.js:100:35
    at async file:///C:/Users/rjoydip/codebase/oss-issue-solving/neverthrow/564/main_test.ts:15:18
    at async innerWrapped (ext:cli/40_test.js:191:5)
    at async exitSanitizer (ext:cli/40_test.js:107:27)
    at async outerWrapped (ext:cli/40_test.js:134:14),
}
```

**Comment by thelinuxlich** [comment]
Should we close this one?

**Comment by jog068** [comment]
Yea, it does work, I'll close it.
